name: All hail Minazo bot

on: pull_request
      
jobs:
  danger:
    runs-on: ubuntu-latest
    if: github.event_name  == 'pull_request'  # if only run pull request when multiple trigger workflow
    steps:
    - uses: actions/checkout@v1

    - run: |
        sudo apt-get -y install clang-format

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true  # runs 'bundle install' and caches installed gems automatically
        working-directory: '.github'
 
    - uses: MeilCli/danger-action@v5
      with:
        plugins_file: '.github/Gemfile'
        danger_file: '.github/Dangerfile'
        danger_id: 'danger-pr'
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
